### ISSUE TITLE
Application freezes under undetermined conditions

### ISSUE THREAD

**Issue by nt4f04uNd** [tanhakabir/SwiftAudioPlayer#52] opened 2020-10-28 13:10 UTC
Actually, it doesnt freeze, becuase I use Flutter, which has it's own rendering threads, but it stops receiving any touch events.
Seems to be like the seek function causes that.
This is what I see in the debugger when I click the debugger pause button at any time when application is frozen.

UPD: it almost 100% happens when I seek to the very end of file, and also sometimes if I try to seek fast.

![image](https://user-images.githubusercontent.com/39104740/97439903-d3aa9680-1937-11eb-8a97-913765b7a155.png)

**Comment by nt4f04uNd** [comment] 2020-10-29 18:26
Investigating deeper, found out that apperantly deadlock happens internally deeply in the AVAudioEngine. My guess is that saying 
```swift
/**
     The UI would freeze when we tried to call playerNode.stop() while
     simultaneously filling a buffer on another thread. Solution was to put
     playerNode related commands in a DispatchQueue
     */
```

you accomplished this only partially. You put only `scheduleBuffer()` and `stop()` there, but for example `pause()` ins't dispatched in the queue, and I assume that's the race condition and causes the deadlock internally in the AVFoundation

https://github.com/tanhakabir/SwiftAudioPlayer/blob/2abba6f0ccd53acb5aa649c498ede09baab4f1ae/Source/Engine/AudioStreamEngine.swift#L72-L83

**Comment by LordSaac** [comment] 2020-11-17 02:42
I have this problem :(

**Comment by nt4f04uNd** [comment] 2020-11-18 12:28
@LordSaac I just commeted out the `pause` function call that I mentioned above in the `numberOfBuffersScheduledInTotal` setter. Seemed to fix the problem, but I'm not sure, as well as why would she put this line in there. If you have much time to test it out, you could try synchronously dispatch it, same as here https://github.com/tanhakabir/SwiftAudioPlayer/blob/2abba6f0ccd53acb5aa649c498ede09baab4f1ae/Source/Engine/AudioStreamEngine.swift#L262-L264

**Comment by LordSaac** [comment] 2020-11-19 02:10
I tried remove line code 262, 263 and 264 in AudioStream Engine, but the issue is linger. :(

Then remove the  queue.sync but is equal.   
:(

**Comment by LordSaac** [comment] 2020-11-19 02:20
Another question the class  SAPlayer.shared is never closing ? 
I use stopStreamingRemoteAudio and    SAPlayer.shared.clear() but 
 the class is always is open, when re open my controller. 

I think if could close the SAPlayer, could solution the problem with freezes screen.

**Comment by nt4f04uNd** [comment] 2020-11-19 02:40
@LordSaac you can try extract the sense of my comment if you gently read it. I said that I commented out the https://github.com/tanhakabir/SwiftAudioPlayer/blob/2abba6f0ccd53acb5aa649c498ede09baab4f1ae/Source/Engine/AudioStreamEngine.swift#L76
not the ones (262, 263, 264) you decided for some reason

**Comment by LordSaac** [comment] 2020-11-20 18:41
Hello @nt4f04uNd ,  I Commented `pause()` did not fail again, and QA approve the test.

Thanks so much for you support :)

**Comment by nt4f04uNd** [comment] 2020-11-28 13:47
@LordSaac I discovered it causes a bug when playback sorta jumps between two buffers. Appertly this was caused by commenting out this line. Wrapping my mind round it I tried wrapping it with this code and I can't believe that actually worked for some reason 🤷‍♂️
```swift
if numberOfBuffersScheduledInTotal == 0 {
   queue.async { [weak self] in
      self?.pause()
   }
}
```
Haven't spent much time on testing this but seems to be working

**Comment by tanhakabir** [comment] 2021-02-23 06:29
Hey @nt4f04uNd you're totally right. In the streaming engine we need to handle the playback operations in a DispatchQueue to prevent weird states/deadlocks. I missed that I wasn't handling that for the pause function of the engine. Will fix now

**Closed** 2021-02-23 06:32 UTC
